version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: telegram_bot
      POSTGRES_PASSWORD: telegram_bot_password
      POSTGRES_DB: telegram_sales_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U telegram_bot"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://telegram_bot:telegram_bot_password@db/telegram_sales_bot
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./logs:/app/logs
    command: >
      sh -c "
        alembic upgrade head &&
        python -m app.main
      "

volumes:
  postgres_data:
