version: '3.8'

services:
  # Serviço da API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama2
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=False
    depends_on:
      - ollama
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - ollama-network

  # Serviço do Ollama
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - ollama-network
    # Comando para baixar o modelo automaticamente
    command: >
      sh -c "
        ollama serve &
        sleep 10 &&
        ollama pull llama2 &&
        wait
      "

volumes:
  ollama_data:
    driver: local

networks:
  ollama-network:
    driver: bridge
